apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
  # Finalizer - project is not deleted until it is not referenced by any appl
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  description: Raf sample description project1
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/rafal321/from-git.git'

# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/