apiVersion: argoproj.io/v1alpha1
kind: AppProject # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/project.yaml
metadata:
  name: project2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/rafal321/from-git.git'

