apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: postgresql
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  REPLICATION_PASSWORD: cmVwbGljYXRpb25QYXNzd29yZA==
  REPLICATION_USER: cmVwbGljYXRpb251c2Vy


# kubectl -n postgresql create secret generic postgresql \
#   --from-literal POSTGRES_USER="postgresadmin" \
#   --from-literal POSTGRES_PASSWORD='admin123' \
#   --from-literal POSTGRES_DB="postgres" \
#   --from-literal REPLICATION_USER="replicationuser" \
#   --from-literal REPLICATION_PASSWORD='replicationPassword' --dry-run=client -oyaml > 1-secret.yaml