apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-depl
  namespace: project2-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      color: green
  template:
    metadata:
      labels:
        app: nginx
        color: green
    spec:
      containers:
      - name: nginx
        image: therafk/webapp:1.5
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: custom-svc
  namespace: project2-ns
spec:
  selector:
    app: nginx
    color: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80