apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds

  instances: 3
  router:
    instances: 1
  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "gp3-exp"
    resources:
      requests:
        storage: 10Gi
  mycnf: |
    [mysqld]
    lower_case_table_names=1
    innodb_buffer_pool_size=256M
    log_bin_trust_function_creators=1


# =======================================
# initDB:
#   clone:
#     donorUrl: mycluster-0.mycluster-instances.another.svc.cluster.local:3306
#     rootUser: root
#     secretKeyRef:
#       name: mypwds

# mycluster.mysql-cluster2.svc.cluster.local