---
apiVersion: argoproj.io/v1alpha1
kind: Application         # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
metadata:
  name: app-automated-sync2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: no-automated-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/v06-sync-policy/my-app6
    repoURL: https://github.com/rafal321/from-git.git
    targetRevision: master
  syncPolicy:
  # automated: {}  sync is refreshed ever 6 min this allows synk when refreshed
    automated:      # this allows delete resources as well when syced
      prune: true
    syncOptions:
      - CreateNamespace=true
