---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rk-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafal321/from-git.git
    targetRevision: HEAD
    path: my-app1
  destination:
    server: https://kubernetes.default.svc