apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: my-app1
  labels:
    app: nginx
    color: blue
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
      color: blue
  template:
    metadata:
      labels:
        app: nginx
        color: blue
    spec:
      containers:
      - name: nginx
        image: therafk/apache2:b
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-app1-svc
  namespace: my-app1
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: nginx
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# kubectl run curl --image=alpine/curl:8.2.1 -n kube-system -i --tty --rm -- sh
# while true; do curl -s myapp.default:8080 | grep -e "--"; sleep 1; done
# <h1>-- BLUE | .....</h1>
# <h1>-- BLUE | .....</h1>
# <h1>-- .... | GREEN</h1>
# <h1>-- .... | GREEN</h1>
