---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-server-secrets
  namespace: mysql-server
data:
  mysqlRootPassword: c2FraWxhW10x
  mysqlUser: aWJl
  mysqlPassword: YWRtaW4=

# echo -n XXX | base64